[package]
name = "sass-color-generator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prisma = "0.1.1"
clap = "2.33.3"
angular-units = "0.2.4"